print('Tabuada de qualquer número')
n = int(input('Quer saber a tabuada de qual número? '))
print(f'{n}X1 = {n*1}')
print(f'{n}X2 = {n*2}')
print(f'{n}X3 = {n*3}')
print(f'{n}X4 = {n*4}')
print(f'{n}X5 = {n*5}')
print(f'{n}X6 = {n*6}')
print(f'{n}X7 = {n*7}')
print(f'{n}X8 = {n*8}')
print(f'{n}X9 = {n*9}')
print(f'{n}X10 = {n*10}')
